---
- hosts: test
  vars_files:
    - files/vault.yml
  pre_tasks:
    # Need to update apt-get to ensure that the latest packages are installed.
    - name: Update Apt-Get
      become: true
      apt: update_cache=yes force_apt_get=yes upgrade=yes

  tasks:
    - name: Set SSH Key
      become: true
      ansible.builtin.shell: |
        echo ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHrODiVwzLuqJOOUj8RfL+X9jn8K/wMujouCelQvRbJs >> /home/dfields/.ssh/authorized_keys

    # Need to create I2P user.
    - name: Create I2P User
      ansible.builtin.user:
        name: i2p

    # Need to install Java 8 for I2P.
    - name: Install JRE
      apt:
        name: default-jre
        state: present

    # Instead of installing I2P+ from the java file, we will use an already compiled version.
    - name: Download I2P
      ansible.builtin.get_url:
        url: https://stormycloud.org/i2p/i2p_plus.zip
        dest: /tmp
        username: "{{ wget_user }}"
        password: "{{ wget_pw }}"

    # Instead of installing I2P+ from the java file, we will use an already compiled version.
    - name: Download DOT_I2P
      ansible.builtin.get_url:
        url: https://stormycloud.org/i2p/doti2p_plus.zip
        dest: /tmp
        username: "{{ wget_user }}"
        password: "{{ wget_pw }}"

    - name: Extract /home/i2p/i2p
      unarchive:
        src: /tmp/i2p_plus.zip
        dest: /home/i2p/
        remote_src: yes

    - name: Extract /home/.i2p/
      unarchive:
        src: /tmp/doti2p_plus.zip
        dest: /home/i2p/
        remote_src: yes

    # Setting permissions for I2P.
    - name: Fix I2P Permissions
      become: true
      ansible.builtin.shell: |
        chown -R i2p:i2p /home/i2p/
        chmod +x /home/i2p/i2p/i2prouter

    # Create firewall rule to allow port I2P traffic. Note UFW is enable on our base image already.
    - name: Enable and set UFW rules
      become: true
      become_user: root
      ansible.builtin.shell: |
        ufw allow 7777
        ufw default allow outgoing
        ufw default deny incoming

    # Need to start I2P to generate configuration files.
    - name: Start I2P
      ansible.builtin.shell: /bin/su i2p -c "/home/i2p/i2p/i2prouter start"

    # Need to stop I2P to add ports to configuration file.
    - name: Stop I2P
      ansible.builtin.shell: /bin/su i2p -c "/home/i2p/i2p/i2prouter stop"

    # We use static ports for I2P. This is to ensure that the ports are always the same and across all I2P instances.
    - name: Add Ports
      become: true
      ansible.builtin.shell: |
        echo i2np.udp.port=7777 >> /home/i2p/.i2p/router.config
        echo i2np.udp.internalPort=7777 >> /home/i2p/.i2p/router.config
        echo router.sharePercentage=90 >> /home/i2p/.i2p/router.config
        echo router.updateDevSU3=true >> /home/i2p/.i2p/router.config
        echo router.updateDevSU3URL=http://skank.i2p/dev/i2pupdate.zip >> /home/i2p/.i2p/router.config
        echo router.updatePolicy=install >> /home/i2p/.i2p/router.config
        echo router.updateThroughProxy=true >> /home/i2p/.i2p/router.config
        echo router.updateURL=http://echelon.i2p/i2p/i2pupdate.su2,http://stats.i2p/i2p/i2pupdate.su2 >> /home/i2p/.i2p/router.config
        echo router.updateUnsigned=true >> /home/i2p/.i2p/router.config
        echo router.updateUnsignedURL=http://skank.i2p/dev/i2pupdate.zip >> /home/i2p/.i2p/router.config
        echo routerconsole.advanced=true >> /home/i2p/.i2p/router.config
        echo i2np.bandwidth.inboundBurstKBytes=1953105 >>  /home/i2p/.i2p/router.config
        echo i2np.bandwidth.inboundBurstKBytesPerSecond=97655 >>  /home/i2p/.i2p/router.config
        echo i2np.bandwidth.inboundKBytesPerSecond=97605 >>  /home/i2p/.i2p/router.config
        echo i2np.bandwidth.outboundBurstKBytes=1953105 >>  /home/i2p/.i2p/router.config
        echo i2np.bandwidth.outboundBurstKBytesPerSecond=97655 >>  /home/i2p/.i2p/router.config
        echo i2np.bandwidth.outboundBurstKBytesPerSecond=97655 >>  /home/i2p/.i2p/router.config
        echo router.floodfillParticipant=true >> /home/i2p/.i2p/router.config

    - name: Create the i2p.service file
      copy:
        dest: /etc/systemd/system/i2p.service
        content: |
          [Unit]
          Description=I2P Service
          After=network.target

          [Service]
          Type=forking
          User=i2p
          ExecStart=/home/i2p/i2p/i2prouter start
          ExecStop=/home/i2p/i2p/i2prouter stop
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable the i2p service
      systemd:
        name: i2p
        enabled: yes

    - name: Start the i2p service
      systemd:
        name: i2p
        state: started

    # Delete the zip files that were downloaded.
    - name: Delete dotnet_i2p.zip
      ansible.builtin.file:
        path: /tmp/doti2p_plus.zip
        state: absent

    - name: Delete i2p.zip
      ansible.builtin.file:
        path: /tmp/i2p_plus.zip
        state: absent

    # Custom Config
    - name: Install TinyProxy
      apt:
        name: tinyproxy
        state: present

    - name: Deploy tinyproxy configuration from vault
      copy:
        content: "{{ tinyproxy_config }}"
        dest: /etc/tinyproxy/tinyproxy.conf
        owner: root
        group: root
        mode: '0644'

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present
        update_cache: yes

    - name: Add Tor repository to sources.list.d
      copy:
        dest: /etc/apt/sources.list.d/tor.list
        content: |
          deb     [signed-by=/usr/share/keyrings/deb.torproject.org-keyring.gpg] https://deb.torproject.org/torproject.org jammy main
          deb-src [signed-by=/usr/share/keyrings/deb.torproject.org-keyring.gpg] https://deb.torproject.org/torproject.org jammy main
        owner: root
        group: root
        mode: '0644'

    - name: Add the GPG key for Tor packages
      command: >
        wget -qO- https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc |
        gpg --dearmor |
        tee /usr/share/keyrings/deb.torproject.org-keyring.gpg >/dev/null
      args:
        creates: /usr/share/keyrings/deb.torproject.org-keyring.gpg

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Tor and deb.torproject.org-keyring
      apt:
        name:
          - tor
          - deb.torproject.org-keyring
        state: present

    - name: Download and execute New Relic install script
      shell: |
        curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash

    - name: Configure New Relic CLI with API key and account ID
      shell: |
        sudo NEW_RELIC_API_KEY={{ new_relic_api_key }} NEW_RELIC_ACCOUNT_ID={{ new_relic_account_id }} /usr/local/bin/newrelic install -y --tag Type:i2p
      environment:
        NEW_RELIC_API_KEY: "{{ new_relic_api_key }}"
        NEW_RELIC_ACCOUNT_ID: "{{ new_relic_account_id }}"
      args:
        executable: /bin/bash