---
- name: Install and Configure Node Exporter
  hosts: i2p
  vars_files:
    - files/vault.yml
  become: true
  tasks:
    - name: Download Node Exporter
      ansible.builtin.shell: ufw allow from 172.16.1.4
