---
  - name: Install and Configure Node Exporter
    hosts: i2p
    vars_files:
      - files/vault.yml
    become: true

    pre_tasks:
    # Need to update apt-get to ensure that the latest packages are installed.
    - name: Update Apt-Get
      become: true
      apt: update_cache=yes force_apt_get=yes upgrade=yes


    tasks:

    - name: Deploy new tinyproxy configuration
      copy:
        content: "{{ tinyproxy_config }}"
        dest: /etc/tinyproxy/tinyproxy.conf
        owner: root
        group: root
        mode: '0644'

    - name: Allow UFW from new IP
      become: true
      ansible.builtin.shell: |
        ufw allow from {{ static_ip }}


